/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * An enumeration.
 */
export enum CloseSessionSessionCloseStatusEnumEnum {
  Closed = "closed",
}

export class CloseSession extends SpeakeasyBase {
  /**
   * Closes the session and starts the ingestion of the uploaded files.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "status" })
  status?: CloseSessionSessionCloseStatusEnumEnum;
}
