/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Filters you can use to narrow down the search. For more information, see [metadata filtering](https://docs.haystack.deepset.ai/docs/metadata-filtering).
 */
export class CountDocumentsParamsHaystackFilters extends SpeakeasyBase {}

export class CountDocumentsParams extends SpeakeasyBase {
    /**
     * Filters you can use to narrow down the search. For more information, see [metadata filtering](https://docs.haystack.deepset.ai/docs/metadata-filtering).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "filters" })
    @Type(() => CountDocumentsParamsHaystackFilters)
    filters?: CountDocumentsParamsHaystackFilters;

    @SpeakeasyMetadata()
    @Expose({ name: "only_documents_without_embedding" })
    onlyDocumentsWithoutEmbedding?: boolean;

    /**
     * Specifies if documents should be prefiltered in the document store instead of within the retriever.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "use_prefiltering" })
    usePrefiltering?: boolean;
}
