/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * An enumeration.
 */
export enum CreateSessionFileWriteModeEnumEnum {
  Keep = "KEEP",
  Overwrite = "OVERWRITE",
  Fail = "FAIL",
}

export class CreateSession extends SpeakeasyBase {
  /**
   * Determines how to handle files that already exist. You can KEEP the existing file, OVERWRITE it, or FAIL to ingest if a file with the same name is already in your workspace.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "write_mode" })
  writeMode?: CreateSessionFileWriteModeEnumEnum;
}
