/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CreateModelRegistryToken extends SpeakeasyBase {
  /**
   * The Hugging Face token.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "token" })
  token: string;
}
