/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Successful Response
 */
export class DCDocumentCount extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count: number;
}
