/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Content of the document.
 */
export class DeepsetCloudDocumentContentContent extends SpeakeasyBase {}

/**
 * Type of the content.
 */
export enum DeepsetCloudDocumentContentType {
    Text = "text",
    Table = "table",
    Image = "image",
    Audio = "audio",
}

/**
 * Object containing the `file_id` and `name` of a file. This is used to associate a document with a file.
 */
export class DeepsetCloudDocumentFileReferenceObjectDeprecatedUseFilesInstead extends SpeakeasyBase {}

/**
 * The metadata of this document.
 */
export class DeepsetCloudDocumentMetadataOfFile extends SpeakeasyBase {}

/**
 * Successful Response
 */
export class DeepsetCloudDocument extends SpeakeasyBase {
    /**
     * Content of the document.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "content" })
    content?: any;

    /**
     * Type of the content.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "content_type" })
    contentType: DeepsetCloudDocumentContentType;

    /**
     * Embedding of the document.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "embedding" })
    embedding?: number[];

    /**
     * Object containing the `file_id` and `name` of a file. This is used to associate a document with a file.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "file" })
    @Type(() => DeepsetCloudDocumentFileReferenceObjectDeprecatedUseFilesInstead)
    file?: DeepsetCloudDocumentFileReferenceObjectDeprecatedUseFilesInstead;

    /**
     * ID of the document.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The metadata of this document.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    @Type(() => DeepsetCloudDocumentMetadataOfFile)
    meta: DeepsetCloudDocumentMetadataOfFile;

    /**
     * Unique identifier of the result.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "result_id" })
    resultId?: string;

    /**
     * Shows the relevance score of the prediction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "score" })
    score?: number;
}
