/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PipelineIndexingStatus } from "./pipelineindexingstatus";
import { Expose, Type } from "class-transformer";

/**
 * Successful Response
 */
export class DocumentStore extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "indexing" })
  @Type(() => PipelineIndexingStatus)
  indexing: PipelineIndexingStatus;

  @SpeakeasyMetadata()
  @Expose({ name: "return_embedding" })
  returnEmbedding: boolean;

  @SpeakeasyMetadata()
  @Expose({ name: "similarity" })
  similarity: string;
}
