/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EvaluationSetWithStatus } from "./evaluationsetwithstatus";
import { Expose, Type } from "class-transformer";

/**
 * Successful Response
 */
export class EvaluationSetPagination extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: EvaluationSetWithStatus })
    @Expose({ name: "data" })
    @Type(() => EvaluationSetWithStatus)
    data: EvaluationSetWithStatus[];

    @SpeakeasyMetadata()
    @Expose({ name: "has_more" })
    hasMore: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "total" })
    total: number;
}
