/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EvalRunName } from "./evalrunname";
import { Expose, Type } from "class-transformer";

/**
 * Your experiment was created.
 */
export class EvalRunCreateResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "data" })
  @Type(() => EvalRunName)
  data: EvalRunName;
}
