/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class File extends SpeakeasyBase {
  /**
   * The total number of characters in this file.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "characters" })
  characters: number;

  /**
   * Datetime object, specifies when the file was created
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt: Date;

  /**
   * Unique identifier of a file.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "file_id" })
  fileId: string;

  /**
   * List of languages in that file.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "languages" })
  languages?: string[];

  /**
   * Metadata of a file.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "meta" })
  meta: Record<string, any>;

  /**
   * Name of the file
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * Size of the file in bytes.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "size" })
  size: number;

  /**
   * The url path of the file.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "url" })
  url: string;
}
