/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class LogEntry extends SpeakeasyBase {
  /**
   * The date and time when the log entry was created.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt: Date;

  /**
   * The log level. Can be one of 'error', 'warning', 'info', 'debug'.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "level" })
  level: string;

  /**
   * The log message.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "msg" })
  msg: string;
}
