/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ModelMeta extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "pipeline_tag" })
    pipelineTag?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "private" })
    private: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "provider" })
    provider: string;
}
