/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Successful Response
 */
export class Notebook extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "link" })
    link: string;
}
