/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Successful Response
 */
export class OrganizationName extends SpeakeasyBase {
    /**
     * Unique name of an organization
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;
}
