/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SessionFile } from "./sessionfile";
import { Expose, Type } from "class-transformer";

/**
 * Returns a list of files registered to the session.
 */
export class PaginatedSessionFile extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: SessionFile })
    @Expose({ name: "data" })
    @Type(() => SessionFile)
    data: SessionFile[];

    /**
     * Whether the session has more files.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "has_more" })
    hasMore: boolean;

    /**
     * The total number of files in the session.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total" })
    total: number;
}
