/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class PatchSharedPrototype extends SpeakeasyBase {
  /**
   * Explain how you expect the users to use this pipeline. Users who visit the shared prototype will see this text. For more information on how to set the right expectations regarding your pipeline, see [Guidelines for Onboarding Your Users](https://docs.cloud.deepset.ai/docs/guidelines-for-onboarding-your-users).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * Select `True` if you want your users to be able to see the files.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "show_files" })
  showFiles?: boolean;

  /**
   * Select `True` if you want your users to be able to filter the documents by metadata.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "show_metadata_filters" })
  showMetadataFilters?: boolean;
}
