/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Returns the pipeline as YAML.
 */
export class PipelineYaml extends SpeakeasyBase {
    /**
     * YAML string of a pipeline
     */
    @SpeakeasyMetadata()
    @Expose({ name: "yaml" })
    yaml: string;
}
