/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Successful Response
 */
export class PipelineStatistics extends SpeakeasyBase {
    /**
     * The accuracy of answers is calculated by dividing the total number of positive feedback by the total number of given feedback. Pipelines with feedback on multiple responses will be counted only once.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "accuracy_of_answers" })
    accuracyOfAnswers?: number;

    /**
     * The average number of feedback messages per query.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "avg_feedback_per_query" })
    avgFeedbackPerQuery?: number;

    /**
     * The number of answers marked as correct.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "correct_answers" })
    correctAnswers?: number;

    /**
     * The total number of experiments created for this pipeline.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "experiments_created" })
    experimentsCreated?: number;

    /**
     * The total number of files indexed for this pipeline.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "indexed_files" })
    indexedFiles?: number;

    /**
     * The average latency of the queries in seconds.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "latency" })
    latency?: number;

    /**
     * The total number of manual feedback inputs provided by users for this pipeline.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "manual_feedback_input" })
    manualFeedbackInput?: number;

    /**
     * The total number of documents created for this pipeline.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_documents" })
    totalDocuments?: number;

    /**
     * The total number of queries for this pipeline.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_queries" })
    totalQueries?: number;

    /**
     * The total number of unique feedback messages the users provided for the results of this pipeline.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "users_provided_feedback" })
    usersProvidedFeedback?: number;

    /**
     * The number of answers marked as wrong.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "wrong_answers" })
    wrongAnswers?: number;

    /**
     * The number of answers marked as wrong by the user while the document was marked as correct.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "wrong_answers_with_correct_document" })
    wrongAnswersWithCorrectDocument?: number;
}
