/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Metadata for the pipeline's index.
 */
export class PipelineFieldSearchResult extends SpeakeasyBase {
    /**
     * A list of fields that you searched for.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    data: string[];

    /**
     * Whether the paginated result has more results.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "has_more" })
    hasMore: boolean;

    /**
     * The total number of results matching your query.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total" })
    total: number;
}
