/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The configuration parameters of this pipeline component
 */
export class PipelineNodeConfigPipelineParameters extends SpeakeasyBase {}

export class PipelineNodeConfig extends SpeakeasyBase {
    /**
     * The configuration parameters of this pipeline component
     */
    @SpeakeasyMetadata()
    @Expose({ name: "params" })
    @Type(() => PipelineNodeConfigPipelineParameters)
    params: PipelineNodeConfigPipelineParameters;

    /**
     * Python class name of the node.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: string;
}
