/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Your pipeline was created.
 */
export class PipelineName extends SpeakeasyBase {
    /**
     * Name of the pipeline
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;
}
