/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class PostPipelineFeedback extends SpeakeasyBase {
  /**
   * Feedback if the answer was correct
   */
  @SpeakeasyMetadata()
  @Expose({ name: "is_correct_answer" })
  isCorrectAnswer: boolean;

  /**
   * Feedback if the document was matched correctly
   */
  @SpeakeasyMetadata()
  @Expose({ name: "is_correct_document" })
  isCorrectDocument: boolean;

  @SpeakeasyMetadata()
  @Expose({ name: "result_id" })
  resultId: string;

  /**
   * A list of tags associated with the feedback.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "tags" })
  tags?: string[];
}
