/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Successful Response
 */
export class SearchSessionPostResponse extends SpeakeasyBase {
  /**
   * The ID of the search session.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "search_session_id" })
  searchSessionId: string;
}
