/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SearchHistory } from "./searchhistory";
import { Expose, Type } from "class-transformer";

/**
 * Successful Response
 */
export class SearchHistoryPagination extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: SearchHistory })
    @Expose({ name: "data" })
    @Type(() => SearchHistory)
    data: SearchHistory[];

    @SpeakeasyMetadata()
    @Expose({ name: "has_more" })
    hasMore: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "total" })
    total?: number;
}
