/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class SearchCount extends SpeakeasyBase {
    /**
     * Number of queries that were sent.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count: number;

    /**
     * Date of the counted search queries.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "date" })
    date: string;
}
