/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DeepsetCloudQueryResponse } from "./deepsetcloudqueryresponse";
import { Expose, Type } from "class-transformer";

/**
 * Returns the search results.
 */
export class SearchResult extends SpeakeasyBase {
  /**
   * The search query
   */
  @SpeakeasyMetadata()
  @Expose({ name: "query_id" })
  queryId?: string;

  /**
   * List of search results.
   */
  @SpeakeasyMetadata({ elemType: DeepsetCloudQueryResponse })
  @Expose({ name: "results" })
  @Type(() => DeepsetCloudQueryResponse)
  results: DeepsetCloudQueryResponse[];
}
