/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ServerStateEnum } from "./serverstateenum";
import { ServerTypeEnum } from "./servertypeenum";
import { Expose } from "class-transformer";

/**
 * Successful Response
 */
export class Server extends SpeakeasyBase {
  /**
   * An enumeration.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "server_type" })
  serverType: ServerTypeEnum;

  /**
   * An enumeration.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "state" })
  state: ServerStateEnum;
}
