/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * An enumeration.
 */
export enum ServerType {
    CpuServer = "cpu-server",
    GpuServer = "gpu-server",
    Unknown = "unknown",
}
