/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ServerState } from "./serverstate";
import { ServerType } from "./servertype";
import { Expose } from "class-transformer";

/**
 * Successful Response
 */
export class Server extends SpeakeasyBase {
  /**
   * An enumeration.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "server_type" })
  serverType: ServerType;

  /**
   * An enumeration.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "state" })
  state: ServerState;
}
