/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Tag extends SpeakeasyBase {
    /**
     * Name of the tag
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * Unique identifier of the tag
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tag_id" })
    tagId: string;
}
