/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform, Type } from "class-transformer";

/**
 * The request configuration used for uploading files. Set each file key to `<org_id>/<workspace_id>/<session_id>/${filename}`, where filename is <file_name>.<txt|pdf> or <file_name>.<txt|pdf>.meta.json for meta files.
 */
export class UploadSessionPresignedPrefix extends SpeakeasyBase {
    /**
     * The fields to include in the request to the presigned URL. These fields are required in the body of each request.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fields" })
    fields: Record<string, string>;

    /**
     * The presigned URL to upload the file to. This URL was generated using the AWS ShareObjectPresignedUrl feature. To learn more, see [AWS Documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url: string;
}

/**
 * Your session is created.
 */
export class UploadSession extends SpeakeasyBase {
    /**
     * The request configuration used for uploading files. Set each file key to `<org_id>/<workspace_id>/<session_id>/${filename}`, where filename is <file_name>.<txt|pdf> or <file_name>.<txt|pdf>.meta.json for meta files.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "aws_prefixed_request_config" })
    @Type(() => UploadSessionPresignedPrefix)
    awsPrefixedRequestConfig: UploadSessionPresignedPrefix;

    /**
     * The URL to the documentation of the session.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "documentation_url" })
    documentationUrl?: string;

    /**
     * The time when the session expires.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expires_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    expiresAt: Date;

    /**
     * Unique identifier of a session.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "session_id" })
    sessionId?: string;
}
