/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class UserName extends SpeakeasyBase {
  /**
   * Family name of a user
   */
  @SpeakeasyMetadata()
  @Expose({ name: "family_name" })
  familyName: string;

  /**
   * Given name of a user
   */
  @SpeakeasyMetadata()
  @Expose({ name: "given_name" })
  givenName: string;
}
