/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Supported languages within a workspace.
 */
export class WorkspaceWorkspaceLanguages extends SpeakeasyBase {}

/**
 * Metadata for workspaces.
 */
export class WorkspaceWorkspaceMeta extends SpeakeasyBase {}

/**
 * Successful Response
 */
export class Workspace extends SpeakeasyBase {
    /**
     * Default idle timeout for pipelines. Pipelines will be marked as idle after this time. Reach out to support to increase this limit.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "default_idle_timeout_in_seconds" })
    defaultIdleTimeoutInSeconds?: number;

    /**
     * Supported languages within a workspace.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "languages" })
    @Type(() => WorkspaceWorkspaceLanguages)
    languages?: WorkspaceWorkspaceLanguages;

    /**
     * Metadata for workspaces.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata_fields" })
    @Type(() => WorkspaceWorkspaceMeta)
    metadataFields?: WorkspaceWorkspaceMeta;

    /**
     * How do you want to name your workspace? Type a name that's longer than 3 characters.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * Unique identifier of a workspace.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "workspace_id" })
    workspaceId: string;
}
