/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetAllDocumentsApiV1WorkspacesWorkspaceNameIndexesIndexNameDocumentsGetSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    httpBearer: string;
}

export class GetAllDocumentsApiV1WorkspacesWorkspaceNameIndexesIndexNameDocumentsGetRequest extends SpeakeasyBase {
    /**
     * The name of the pipeline used to process the documents.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=index_name" })
    indexName: string;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=return_embedding" })
    returnEmbedding?: boolean;

    /**
     * Type the name of the workspace.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=workspace_name" })
    workspaceName: string;
}

export class GetAllDocumentsApiV1WorkspacesWorkspaceNameIndexesIndexNameDocumentsGetResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Successful Response
     */
    @SpeakeasyMetadata({ elemType: shared.DeepsetCloudDocument })
    deepsetCloudDocuments?: shared.DeepsetCloudDocument[];

    /**
     * Validation Error
     */
    @SpeakeasyMetadata()
    httpValidationError?: shared.HTTPValidationError;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
