/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class PostNotebookApiV1NotebookPostSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    httpBearer: string;
}

export class PostNotebookApiV1NotebookPostRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: Record<string, any>;

    /**
     * A unique identifier of a pipeline. You can obtain it from the List Pipelines endpoint.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=pipeline_id" })
    pipelineId?: string;
}

export class PostNotebookApiV1NotebookPostResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Validation Error
     */
    @SpeakeasyMetadata()
    httpValidationError?: shared.HTTPValidationError;

    /**
     * Successful Response
     */
    @SpeakeasyMetadata()
    notebook?: shared.Notebook;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
