/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class UpdateTokenApiV1ModelRegistryTokensProviderPutSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
  })
  httpBearer: string;
}

/**
 * The provider of the model registry
 */
export enum UpdateTokenApiV1ModelRegistryTokensProviderPutProviderModelProviderEnum {
  Huggingface = "huggingface",
  Openai = "openai",
  Cohere = "cohere",
}

export class UpdateTokenApiV1ModelRegistryTokensProviderPutRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  updateModelRegistryToken: shared.UpdateModelRegistryToken;

  /**
   * The provider of the model registry
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=provider",
  })
  provider: UpdateTokenApiV1ModelRegistryTokensProviderPutProviderModelProviderEnum;
}

export class UpdateTokenApiV1ModelRegistryTokensProviderPutResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Validation Error
   */
  @SpeakeasyMetadata()
  httpValidationError?: shared.HTTPValidationError;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Successful Response
   */
  @SpeakeasyMetadata()
  updateTokenApiV1ModelRegistryTokensProviderPut201ApplicationJSONAny?: any;
}
