/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class UpdateFileMetaApiV1WorkspacesWorkspaceNameFilesFileIdMetaPutSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    httpBearer: string;
}

export class UpdateFileMetaApiV1WorkspacesWorkspaceNameFilesFileIdMetaPutMeta extends SpeakeasyBase {}

export class UpdateFileMetaApiV1WorkspacesWorkspaceNameFilesFileIdMetaPutRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody: UpdateFileMetaApiV1WorkspacesWorkspaceNameFilesFileIdMetaPutMeta;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=file_id" })
    fileId: string;

    /**
     * Type the name of the workspace.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=workspace_name" })
    workspaceName: string;
}

export class UpdateFileMetaApiV1WorkspacesWorkspaceNameFilesFileIdMetaPutResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Validation Error
     */
    @SpeakeasyMetadata()
    httpValidationError?: shared.HTTPValidationError;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Successful Response
     */
    @SpeakeasyMetadata()
    updateFileMetaApiV1WorkspacesWorkspaceNameFilesFileIdMetaPut200ApplicationJSONAny?: any;
}
